/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as RealEstateIndexRouteImport } from './routes/real-estate.index'
import { Route as RealEstateSlugRouteImport } from './routes/real-estate.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateIndexRoute = RealEstateIndexRouteImport.update({
  id: '/real-estate/',
  path: '/real-estate/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateSlugRoute = RealEstateSlugRouteImport.update({
  id: '/real-estate/$slug',
  path: '/real-estate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/real-estate/$slug': typeof RealEstateSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/real-estate/': typeof RealEstateIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/real-estate/$slug': typeof RealEstateSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/real-estate': typeof RealEstateIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/real-estate/$slug': typeof RealEstateSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/real-estate/': typeof RealEstateIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/insights/$slug'
    | '/projects/$slug'
    | '/real-estate/$slug'
    | '/services/$slug'
    | '/insights/'
    | '/projects/'
    | '/real-estate/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/insights/$slug'
    | '/projects/$slug'
    | '/real-estate/$slug'
    | '/services/$slug'
    | '/insights'
    | '/projects'
    | '/real-estate'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/insights/$slug'
    | '/projects/$slug'
    | '/real-estate/$slug'
    | '/services/$slug'
    | '/insights/'
    | '/projects/'
    | '/real-estate/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  RealEstateSlugRoute: typeof RealEstateSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RealEstateIndexRoute: typeof RealEstateIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate/': {
      id: '/real-estate/'
      path: '/real-estate'
      fullPath: '/real-estate/'
      preLoaderRoute: typeof RealEstateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate/$slug': {
      id: '/real-estate/$slug'
      path: '/real-estate/$slug'
      fullPath: '/real-estate/$slug'
      preLoaderRoute: typeof RealEstateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  RealEstateSlugRoute: RealEstateSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RealEstateIndexRoute: RealEstateIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
