INSERT INTO public.site_settings (id, company_name, company_full_name, tagline, phone, phone_alt, whatsapp, email, email_alt, address, city, map_lat, map_lng, facebook_url, google_maps_url, linkedin_url, pec_number, ntn_number, founded_year, footer_note, offices) VALUES
(1,'AMARC','AMARC Engineering & Construction Company','Engineering the built environment of Pakistan.','+92 42 3577 8800','+92 300 842 1199','+92 300 842 1199','info@amarc.com.pk','projects@amarc.com.pk','12-C, Main Boulevard, Gulberg III','Lahore',31.5204,74.3587,'https://facebook.com/amarcpk','https://maps.google.com/?q=Gulberg+III+Lahore','https://linkedin.com/company/amarcpk','PEC/CONST/OPR/12847','4270183-6',2004,'AMARC Engineering & Construction Company is registered with the Pakistan Engineering Council.','[{"city":"Lahore","label":"Head Office","address":"12-C, Main Boulevard, Gulberg III, Lahore","phone":"+92 42 3577 8800"},{"city":"Karachi","label":"Regional Office","address":"Suite 704, Business Avenue, Shahrah-e-Faisal, Karachi","phone":"+92 21 3452 6610"},{"city":"Islamabad","label":"Regional Office","address":"Office 9, Kohistan Plaza, Blue Area, Islamabad","phone":"+92 51 2870 440"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.home_sections (key,label,eyebrow,heading,subheading,body,cta_label,cta_href,sort_order,extra) VALUES
('hero','Hero','AMARC Engineering & Construction','We build what Pakistan runs on.','From foundation to finishing — design, engineering and delivery under one roof.','Twenty years of turnkey construction across Punjab and Sindh, delivered to international standards and audited at every phase.','Start a project','/contact',1,'{"secondary_label":"See our work","secondary_href":"/projects"}'::jsonb),
('credibility','Credibility strip',NULL,NULL,NULL,NULL,NULL,NULL,2,'{"items":[{"value":"2004","label":"Established"},{"value":"PEC C-A","label":"Licence category"},{"value":"ISO 9001","label":"Certified"},{"value":"3","label":"Regional offices"}]}'::jsonb),
('stats','Stats counters','By the numbers','A record you can audit.','Every figure below is drawn from projects listed in our portfolio.',NULL,NULL,NULL,3,'{"items":[{"value":184,"suffix":"","label":"Projects completed"},{"value":23,"suffix":"","label":"Currently ongoing"},{"value":6.4,"suffix":"M","label":"Sq. ft. delivered"},{"value":41500,"suffix":"M","prefix":"PKR ","label":"Contract value executed"}]}'::jsonb),
('services','Services','What we do','Nine disciplines. One accountable team.','Design, engineering, procurement and construction handled in-house so nothing falls between consultants.',NULL,'View all services','/services',4,'{}'::jsonb),
('sectors','Sectors','Where we build','Sectors we know inside out.','Each sector has its own approvals, standards and risk profile. We staff accordingly.',NULL,NULL,'/projects',5,'{}'::jsonb),
('projects','Featured projects','Portfolio','Recently delivered.','A selection of completed and ongoing work across Pakistan.',NULL,'Browse all projects','/projects',6,'{}'::jsonb),
('process','Process','How we work','Six phases. No surprises.','Every project runs through the same audited sequence, with a written sign-off gate between each phase.',NULL,NULL,NULL,7,'{"steps":[{"title":"Feasibility & survey","body":"Topography, soil investigation, zoning and a costed feasibility report before anything is drawn."},{"title":"Design & engineering","body":"Architectural concept, structural analysis and MEP coordination issued as a single stamped set."},{"title":"Approvals & tendering","body":"LDA / SBCA / CDA submissions, NOC tracking, BOQ preparation and subcontractor tendering."},{"title":"Construction","body":"Self-performed civil works with directly employed site engineers and daily progress reporting."},{"title":"QA/QC & HSE","body":"Third-party material testing, weekly safety audits and a documented non-conformance register."},{"title":"Handover & O&M","body":"As-built drawings, snag closure, warranty pack and a twelve-month defects liability period."}]}'::jsonb),
('developments','Developments','Real estate','Newly launched developments.','Our own developments, built and sold by the same team that designs them.',NULL,'View developments','/real-estate',8,'{}'::jsonb),
('clients','Clients','Trusted by','Clients and partners.',NULL,NULL,NULL,NULL,9,'{}'::jsonb),
('certifications','Certifications','Compliance','Licensed, certified, insured.','Registration and certification details are available for download or verification on request.',NULL,'View certifications','/about/certifications',10,'{}'::jsonb),
('testimonials','Testimonials','References','What clients say.',NULL,NULL,NULL,NULL,11,'{}'::jsonb),
('insights','Insights','Insights','From the site office.','Practical notes on construction cost, regulation and method in Pakistan.',NULL,'Read all insights','/insights',12,'{}'::jsonb),
('cta','Contact CTA','Get in touch','Tell us what you want to build.','Send us the plot details and a rough brief. You will get a written response within two working days.',NULL,'Request a quote','/contact',13,'{}'::jsonb)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.services (slug,title,short_title,icon,summary,description,bullets,process_steps,faqs,sort_order) VALUES
('architectural-design','Architectural Design','Architecture','DraftingCompass','Concept to construction drawings for residential, commercial and institutional buildings.','Our architecture studio takes a project from massing study through to a stamped construction set. We work in Revit, coordinate live with the structural and MEP teams in the same office, and issue a single reconciled drawing package — which is why our sites see far fewer RFIs than the industry norm. Every scheme is tested against local by-laws (LDA, SBCA, CDA, RDA) before a single sheet is issued.','["Concept design and massing studies","3D visualisation and walkthroughs","Working drawings and detail sheets","By-law compliance and authority submission","Material and finishes schedules","Coordination with structural and MEP"]'::jsonb,'["Brief and site appraisal","Concept and options","Design development","Authority submission","Construction documentation"]'::jsonb,'[{"q":"Do you work on plots outside Lahore?","a":"Yes. We regularly deliver architectural packages in Karachi, Islamabad, Rawalpindi, Faisalabad and Multan, and we handle the relevant local authority submissions in each."},{"q":"How long does a house design take?","a":"A typical 1-kanal residence takes six to eight weeks from brief to a full construction set, including one round of authority comments."}]'::jsonb,1),
('structural-design','Structural Design','Structural','Frame','RCC and steel design, seismic analysis and independent structural vetting.','We design reinforced concrete and structural steel frames for buildings up to twenty storeys, plus retaining structures, water-retaining works and industrial foundations. Analysis is carried out in ETABS and SAFE against the Building Code of Pakistan (Seismic Provisions), with peer-reviewed calculations issued alongside every drawing set. We also provide independent structural vetting for clients who want a second opinion on someone else''s design.','["RCC frame and slab design","Structural steel and pre-engineered buildings","Seismic analysis to BCP-SP 2007","Raft, pile and mat foundation design","Retaining walls and basements","Independent third-party vetting"]'::jsonb,'["Load assessment","Analysis modelling","Member design","Detailing and BBS","Peer review and stamping"]'::jsonb,'[{"q":"Do you issue stamped drawings?","a":"Yes — all structural drawings are stamped by a PEC-registered professional engineer."},{"q":"Can you review a design done by another firm?","a":"We do independent vetting regularly, and issue a written report with a clear pass, conditional or fail verdict."}]'::jsonb,2),
('construction-services','Construction Services','Construction','HardHat','Turnkey grey structure and finishing, self-performed with directly employed site teams.','This is the core of the business. We take projects on a turnkey basis — grey structure, finishes, external works and handover — with directly employed site engineers, foremen and QA staff rather than a chain of labour contractors. Clients get a single point of accountability, a weekly progress report with photographs, and a cost position reconciled against the BOQ every month.','["Turnkey grey structure","Complete finishing works","Renovation and vertical extensions","Industrial sheds and warehousing","External development and hardscape","Monthly cost reconciliation"]'::jsonb,'["Mobilisation and site setup","Substructure","Superstructure","Finishes and MEP","Snagging and handover"]'::jsonb,'[{"q":"Do you work on a cost-plus or fixed-price basis?","a":"Both. Most private residential clients prefer fixed-price against a frozen BOQ; institutional clients usually go cost-plus with an agreed management fee."},{"q":"What is the defects liability period?","a":"Twelve months from practical completion as standard, extendable by agreement."}]'::jsonb,3),
('project-management','Project Management','PM','GanttChartSquare','Client-side project management, cost control and construction supervision.','When you already have a contractor, we act for you. Our PM teams run the programme, verify interim payment certificates, chase the approvals, hold the design consultants to their deliverable dates and maintain a live risk register. Clients typically bring us in when a project has slipped or when the value is high enough that independent oversight pays for itself.','["Programme development and tracking","Interim payment certification","Contractor performance monitoring","Change and variation control","Risk register and mitigation","Monthly client reporting"]'::jsonb,'["Baseline programme","Weekly site supervision","Monthly valuation","Variation control","Completion and closeout"]'::jsonb,'[]'::jsonb,4),
('real-estate','Real Estate','Real Estate','Building2','Development, sales and advisory on our own and third-party projects.','Our real estate arm develops residential and mixed-use projects, and advises landowners on the highest-value use for a site. Because the construction team sits in the same building, our feasibility numbers are built from real, current construction rates rather than market averages — which is why our launches hold their delivery dates.','["Land acquisition advisory","Highest-and-best-use studies","Development feasibility and cash-flow modelling","Project launch and sales","Booking and instalment administration","Possession and transfer support"]'::jsonb,'["Site appraisal","Feasibility","Approvals","Launch","Delivery and possession"]'::jsonb,'[{"q":"Do you offer instalment plans?","a":"Yes — most of our developments run on a 36 to 48 month instalment structure with a booking amount, monthly instalments and balloon payments. Full schedules are published on each development page."}]'::jsonb,5),
('material-supplies','Material Supplies','Materials','PackageCheck','Bulk supply of steel, cement, aggregate, block and finishing materials.','We buy at project scale and pass the rate on. Our supply division stocks and delivers deformed steel bar, cement, crush and sand, concrete block, tiles and sanitary ware across Punjab, with mill test certificates supplied on every steel consignment and third-party cube testing available for ready-mix.','["Deformed steel bar with mill certificates","Cement — all major brands","Crush, sand and aggregate","Concrete block and paver","Tiles, sanitary and fittings","Site delivery and unloading"]'::jsonb,'[]'::jsonb,'[]'::jsonb,6),
('contracts-consultancy','Contracts & Consultancy','Contracts','Scale','Contract drafting, claims, BOQ preparation and dispute resolution.','Construction disputes in Pakistan are almost always documentation failures. We draft and review construction contracts, prepare and vet bills of quantity, assemble and defend claims, and act as an expert in arbitration. Our team works to FIDIC and PEC standard forms and has appeared before arbitral tribunals in Lahore and Karachi.','["Contract drafting and review","BOQ preparation and vetting","Rate analysis and market comparison","Claim preparation and defence","Extension-of-time analysis","Arbitration and expert testimony"]'::jsonb,'[]'::jsonb,'[]'::jsonb,7),
('topography-soil-testing','Topography & Soil Testing','Survey & Soil','Mountain','Total-station survey, contour mapping, SPT boreholes and lab soil classification.','Every project we touch starts here. Our survey crew produces total-station topographic surveys and contour plans, and our geotechnical team carries out standard penetration test boreholes with laboratory classification, bearing capacity determination and settlement analysis. Reports are issued in a format accepted by every major approving authority in Pakistan.','["Total-station topographic survey","Contour and level plans","Plot demarcation","SPT boreholes to 30m","Laboratory soil classification","Bearing capacity and settlement report"]'::jsonb,'[]'::jsonb,'[{"q":"How deep do you bore?","a":"Standard practice is three boreholes to 15 metres for a low-rise building and up to 30 metres for high-rise or heavy industrial loads."}]'::jsonb,8),
('interior-design','Interior Design','Interiors','Sofa','Interior architecture, joinery detailing and fit-out execution.','We design and build interiors — residential, corporate office, retail and hospitality. The studio produces full joinery and services detailing rather than mood boards, and the same fit-out team that priced the job executes it, so what gets specified is what gets installed.','["Space planning and interior architecture","Joinery and millwork detailing","Lighting and electrical layouts","FF&E specification and procurement","Turnkey fit-out execution","Corporate and retail rollouts"]'::jsonb,'[]'::jsonb,'[]'::jsonb,9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.sectors (slug,title,icon,summary,description,sort_order) VALUES
('residential','Residential','Home','Houses, apartments and gated housing schemes.','From single-kanal residences in DHA to multi-storey apartment blocks, residential is where AMARC started and still delivers the highest volume of work.',1),
('commercial','Commercial','Store','Offices, retail, plazas and mixed-use.','Commercial work demands speed to revenue. We programme these projects backwards from the tenant handover date.',2),
('industrial','Industrial','Factory','Factories, warehouses, cold stores and process plant civils.','Industrial clients need production uptime. We build around live operations and phase works to keep the plant running.',3),
('infrastructure','Infrastructure','Route','Roads, drainage, water supply and site development.','Public and private infrastructure — carriageways, storm drainage, sewerage and bulk earthworks.',4),
('healthcare','Healthcare','HeartPulse','Hospitals, clinics and diagnostic facilities.','Healthcare construction is governed by infection control, medical gas and redundancy requirements that ordinary contractors miss.',5),
('education','Education','GraduationCap','Schools, colleges and campus buildings.','Campus work runs on the academic calendar. We build to summer-break windows.',6),
('hospitality','Hospitality','UtensilsCrossed','Hotels, restaurants and banquet facilities.','Finish quality is the whole product in hospitality. These projects get our senior fit-out teams.',7),
('institutional','Institutional','Landmark','Government, banking and community buildings.','Institutional projects carry heavy documentation and audit requirements. Our contracts team handles them.',8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.projects (slug,title,client,city,location,sector_slug,status,value_pkr_millions,covered_area,plot_area,storeys,start_date,completion_date,architect,summary,description,scope,is_featured,sort_order) VALUES
('gulberg-corporate-tower','Gulberg Corporate Tower','Meridian Holdings (Pvt) Ltd','Lahore','Main Boulevard, Gulberg III','commercial','completed',1840,'214,000 sq ft','2 kanal','B+G+14','2020-03-01','2023-08-15','AMARC Architecture Studio','A fourteen-storey grade-A office tower with two basement levels, delivered on a fixed-price turnkey contract.','Gulberg Corporate Tower is a B+G+14 commercial building on Main Boulevard with 214,000 sq ft of leasable area, two basement parking levels and a double-height entrance atrium. The structural frame is a post-tensioned flat slab on a raft foundation, which cut the floor-to-floor height by 300mm across fourteen levels and gained the client an additional half floor within the approved height envelope. The project was delivered nine weeks ahead of the contractual completion date.','["Feasibility","Architectural Design","Structural Design","Construction","Project Management"]'::jsonb,true,1),
('dha-phase-8-residence','DHA Phase 8 Private Residence','Private client','Lahore','Block Z, DHA Phase 8','residential','completed',96,'11,400 sq ft','2 kanal','B+G+1','2022-01-10','2023-06-30','AMARC Architecture Studio','A two-kanal contemporary residence with basement, home cinema and landscaped courtyard.','A two-kanal family residence built around a central courtyard, with a full basement housing a home cinema, gymnasium and staff quarters. The elevation uses sandblasted Badal grey stone and exposed board-marked concrete. Interiors, joinery and landscaping were all executed in-house.','["Architectural Design","Structural Design","Construction","Interior Design"]'::jsonb,true,2),
('sundar-industrial-facility','Sundar Industrial Estate Manufacturing Facility','Zafar Textiles Ltd','Lahore','Sundar Industrial Estate','industrial','completed',720,'168,000 sq ft','12 acres','G+1','2019-06-01','2021-02-20','AMARC Architecture Studio','A 168,000 sq ft pre-engineered manufacturing shed with allied civil works and utility block.','A textile manufacturing facility comprising a 168,000 sq ft pre-engineered steel shed on isolated pad foundations, a two-storey RCC administration and utility block, effluent treatment civils, internal roads and a 400kVA substation building. Machine foundations were designed for dynamic loads with isolation pads to keep vibration within tolerance for the ring-frame line.','["Topography & Soil Testing","Structural Design","Construction","Material Supplies"]'::jsonb,true,3),
('bahria-town-apartments','Meadow Court Apartments','Sarwar Developers','Rawalpindi','Bahria Town Phase 7','residential','ongoing',1310,'186,000 sq ft','4 kanal','G+9','2024-04-01','2026-11-30','Studio Kohsar','A 96-unit residential apartment building currently at ninth-floor slab stage.','Meadow Court is a G+9 residential building of 96 apartments in one, two and three-bedroom configurations, with a podium car park, rooftop community deck and standby generation for full-load backup. The project is currently at ninth-floor slab casting with finishing works underway on the lower six floors.','["Structural Design","Construction","Project Management"]'::jsonb,true,4),
('karachi-diagnostic-centre','Shahrah-e-Faisal Diagnostic Centre','Aafiyat Health Network','Karachi','Shahrah-e-Faisal','healthcare','completed',465,'52,000 sq ft','1,100 sq yd','G+5','2021-09-15','2023-04-10','Arif Hasan Associates','A six-level diagnostic and day-care hospital with MRI vault and medical gas reticulation.','A 52,000 sq ft diagnostic facility with radiology, pathology, day-care surgery and consulting floors. The scope included a lead-lined MRI vault with a non-ferrous structural zone, full medical gas reticulation with manifold room, HEPA-filtered air handling to the procedure suites and N+1 redundant power. Commissioned and handed over with all statutory health approvals in place.','["Structural Design","Construction","Project Management","Interior Design"]'::jsonb,true,5),
('johar-town-retail-plaza','Johar Town Retail Plaza','Bilal Estate Holdings','Lahore','Block G1, Johar Town','commercial','completed',380,'46,000 sq ft','1 kanal','B+G+5','2021-02-01','2022-10-05','AMARC Architecture Studio','A six-level retail and office plaza with basement parking, delivered in twenty months.','A mixed retail and office plaza with basement parking, ground and first-floor retail and four office floors above. A glass curtain wall to the boulevard elevation with an aluminium fin screen provides shading on the west face and cut the cooling load by an estimated eighteen per cent.','["Architectural Design","Structural Design","Construction"]'::jsonb,false,6),
('faisalabad-cold-store','Faisalabad Cold Storage Complex','Punjab Agro Foods','Faisalabad','Sargodha Road','industrial','completed',540,'88,000 sq ft','6 acres','G+1','2020-08-01','2022-03-18','AMARC Architecture Studio','An 8,000-tonne controlled-atmosphere cold storage facility with insulated panel envelope.','An 8,000-tonne capacity cold storage complex with twelve controlled-atmosphere chambers, insulated sandwich panel envelope, vapour-sealed floor slab with under-slab heating to prevent frost heave, dock levellers and an ammonia plant room built to the required separation standards.','["Topography & Soil Testing","Structural Design","Construction"]'::jsonb,false,7),
('multan-campus-block','Government College Campus Block','Higher Education Department, Punjab','Multan','Bosan Road','education','completed',298,'64,000 sq ft','4 acres','G+2','2019-03-01','2020-12-22','Nespak (design) / AMARC (build)','A three-storey academic block of twenty-four classrooms and four laboratories.','A three-storey academic block delivered under a Punjab HED contract, containing twenty-four classrooms, four science laboratories, a library and staff facilities. Built to PWD specification with third-party material testing on every concrete pour and a full documentation trail for departmental audit.','["Construction","Contracts & Consultancy"]'::jsonb,false,8),
('ravi-road-widening','Ravi Road Carriageway & Drainage','Lahore Development Authority','Lahore','Ravi Road','infrastructure','completed',412,'3.2 km','—','—','2018-11-01','2020-05-30',NULL,'Dual carriageway widening with box culvert storm drainage over a 3.2 km stretch.','Widening of 3.2 km of Ravi Road to dual two-lane carriageway, including subgrade improvement, wet-mix macadam base, asphaltic wearing course, RCC box culvert storm drainage, kerbing, footpath and street lighting. Traffic was maintained throughout via a phased half-width construction sequence.','["Topography & Soil Testing","Construction","Project Management"]'::jsonb,false,9),
('islamabad-boutique-hotel','Blue Area Boutique Hotel','Serena Hospitality Ventures','Islamabad','Jinnah Avenue, Blue Area','hospitality','ongoing',890,'71,000 sq ft','2,000 sq yd','B+G+7','2025-01-15','2027-03-31','Studio Kohsar','A 64-key boutique hotel with rooftop restaurant, currently in structural phase.','A 64-key boutique hotel comprising a basement plant and parking level, ground-floor lobby and restaurant, six guest floors and a rooftop dining terrace with views to the Margalla Hills. Structure is a shear-wall core with post-tensioned floor plates. Currently at fifth-floor slab.','["Architectural Design","Structural Design","Construction","Interior Design"]'::jsonb,false,10),
('dha-karachi-villas','Creek Vista Villas','Habib Land (Pvt) Ltd','Karachi','DHA Phase 8, Karachi','residential','handed_over',1120,'148,000 sq ft','9 acres','G+1','2018-05-01','2021-09-15','AMARC Architecture Studio','Thirty-two detached villas with shared amenity and full external development.','A gated cluster of thirty-two detached villas of 4,600 sq ft each, with shared clubhouse, pool, internal roads, underground utilities and perimeter security infrastructure. Delivered in three phases so early buyers could take possession ahead of full scheme completion.','["Architectural Design","Structural Design","Construction","Real Estate"]'::jsonb,false,11),
('lahore-bank-rollout','Regional Bank Branch Rollout','Askari Commercial Group','Lahore','14 branches, Punjab','institutional','ongoing',186,'38,000 sq ft','—','—','2025-06-01','2026-09-30','AMARC Interior Studio','A fourteen-branch interior fit-out rollout on a rolling four-week-per-branch programme.','A rolling fit-out programme across fourteen retail bank branches in Punjab, each delivered to an identical brand specification on a four-week site window. Scope covers demolition, partitioning, joinery, strong-room civils, ELV, HVAC modification and signage. Nine branches are complete and operational.','["Interior Design","Construction","Project Management"]'::jsonb,false,12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.developments (slug,title,city,location,status,summary,description,storeys,handover,starting_price,amenities,highlights,unit_types,payment_plan,is_featured,sort_order) VALUES
('amarc-vantage','AMARC Vantage','Lahore','Main Boulevard, Gulberg III','newly_launched','Twenty-two storeys of serviced apartments and offices on Main Boulevard.','AMARC Vantage is our flagship development: a B2+G+22 mixed-use tower on Main Boulevard, Gulberg III, combining four retail levels, eight office floors and ten floors of fully serviced residential apartments. Designed, engineered and built entirely in-house, with a committed handover date backed by a liquidated damages clause in every buyer agreement.','B2+G+22','Q4 2029','PKR 24,500,000','["24/7 security and CCTV","Full-load standby power","High-speed lifts (4 nos.)","Rooftop infinity pool","Residents gymnasium","Two basement parking levels","Concierge and facility management","Fibre-optic connectivity"]'::jsonb,'["Main Boulevard frontage","Delivered by the contractor, not a middleman","Liquidated damages on late handover","Escrowed buyer payments"]'::jsonb,'[{"type":"Studio Apartment","area":"620 sq ft","price":"PKR 24,500,000"},{"type":"1 Bedroom","area":"940 sq ft","price":"PKR 36,200,000"},{"type":"2 Bedroom","area":"1,480 sq ft","price":"PKR 55,800,000"},{"type":"3 Bedroom","area":"2,150 sq ft","price":"PKR 79,400,000"},{"type":"Office Floor Plate","area":"4,200 sq ft","price":"On request"}]'::jsonb,'[{"milestone":"Booking","percent":"15%","note":"On agreement signing"},{"milestone":"Confirmation","percent":"10%","note":"Within 60 days"},{"milestone":"Monthly instalments","percent":"45%","note":"48 equal monthly instalments"},{"milestone":"Half-yearly balloons","percent":"20%","note":"8 balloon payments"},{"milestone":"On possession","percent":"10%","note":"At handover"}]'::jsonb,true,1),
('amarc-courtyard-homes','AMARC Courtyard Homes','Lahore','Sector M, DHA Phase 9 Prism','ongoing','Forty-eight courtyard houses on 10-marla and 1-kanal plots.','A gated cluster of forty-eight courtyard houses in DHA Phase 9 Prism, offered on 10-marla and 1-kanal plots. Each house is built around a private central courtyard that brings daylight into the core of the plan — a response to the deep, narrow plot geometry that makes most DHA houses dark in the middle. Grey structure is complete on the first twenty units.','G+1','Q2 2028','PKR 41,000,000','["Gated community with single entry","Underground utilities","Community park and play area","Mosque within cluster","Wide 40ft internal roads","Piped natural gas"]'::jsonb,'["Courtyard-centred plan","Built and sold by the same team","Structural warranty of ten years"]'::jsonb,'[{"type":"10 Marla Courtyard House","area":"3,400 sq ft","price":"PKR 41,000,000"},{"type":"1 Kanal Courtyard House","area":"5,800 sq ft","price":"PKR 72,500,000"}]'::jsonb,'[{"milestone":"Booking","percent":"20%","note":"On agreement signing"},{"milestone":"Monthly instalments","percent":"50%","note":"36 equal monthly instalments"},{"milestone":"Balloon payments","percent":"20%","note":"6 half-yearly balloons"},{"milestone":"On possession","percent":"10%","note":"At handover"}]'::jsonb,true,2),
('amarc-trade-centre','AMARC Trade Centre','Faisalabad','Susan Road','newly_launched','Retail and wholesale trade floors with dedicated loading and cold rooms.','A purpose-built trade centre on Susan Road offering retail shops on the lower two floors and wholesale trade units above, with a dedicated rear loading dock, freight lift, and cold-room provision for perishable traders. Designed for the way Faisalabad wholesale trade actually operates rather than as a generic shopping plaza.','G+5','Q1 2029','PKR 8,900,000','["Dedicated freight lift","Rear loading dock","Cold room provision","Standby power","Fire detection and suppression","Prayer area and washrooms per floor"]'::jsonb,'["Purpose-built for wholesale trade","Loading separated from customer access"]'::jsonb,'[{"type":"Ground Floor Shop","area":"280 sq ft","price":"PKR 14,600,000"},{"type":"First Floor Shop","area":"320 sq ft","price":"PKR 10,200,000"},{"type":"Trade Unit","area":"640 sq ft","price":"PKR 8,900,000"}]'::jsonb,'[{"milestone":"Booking","percent":"25%","note":"On agreement signing"},{"milestone":"Monthly instalments","percent":"55%","note":"40 equal monthly instalments"},{"milestone":"On possession","percent":"20%","note":"At handover"}]'::jsonb,false,3)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.team_members (name,role,credentials,bio,sort_order) VALUES
('Arshad Mahmood','Founder & Chief Executive','B.Sc. Civil Engineering (UET Lahore), PEC Registered','Founded AMARC in 2004 after eleven years on site with a national contractor. Still reviews every project over PKR 500 million personally.',1),
('Ayesha Rauf','Director, Architecture','B.Arch (NCA Lahore), PCATP Registered','Leads the architecture studio. Twenty years across residential, commercial and healthcare, with a particular interest in passive cooling for Punjab climate.',2),
('Bilal Cheema','Director, Structural Engineering','M.Sc. Structural Engineering (UET Taxila), PEC Registered','Runs structural design and independent vetting. Has stamped over four hundred building designs and appeared as a structural expert in arbitration.',3),
('Nadia Sultan','Head of Contracts & Commercial','LL.B, MRICS','Handles contract drafting, claims and commercial control. Previously with a FIDIC-based consultancy in Dubai.',4),
('Omer Farooq','Head of Construction','B.Sc. Civil Engineering (UET Lahore), NEBOSH IGC','Responsible for all site delivery and HSE across active projects. Eighteen years of self-performed construction experience.',5),
('Hina Javed','Head of Real Estate','MBA (LUMS)','Leads development feasibility, launches and buyer relations for AMARC own developments.',6);

INSERT INTO public.testimonials (author,author_role,company,quote,rating,sort_order) VALUES
('Kamran Sheikh','Managing Director','Meridian Holdings (Pvt) Ltd','They handed over the Gulberg tower nine weeks early on a fixed price, and the monthly cost reports were accurate enough that we never had a surprise. I have not had that experience with any other contractor in Lahore.',5,1),
('Dr. Faisal Aziz','Chief Executive','Aafiyat Health Network','Hospital construction is unforgiving — the medical gas, the MRI vault, the redundancy. AMARC understood all of it without us having to bring in a specialist consultant from abroad.',5,2),
('Zafar Iqbal','Chairman','Zafar Textiles Ltd','They built our Sundar plant around a live production schedule and never once shut us down. The machine foundations were spot on.',5,3),
('Saira Ahmed','Private client','DHA Phase 8, Lahore','The house came out exactly as the drawings promised, which sounds like it should be normal and in Pakistan is not. The joinery in particular is beautiful.',5,4),
('Tariq Sarwar','Director','Sarwar Developers','We brought AMARC in as project managers after our first contractor lost eight months. They rebuilt the programme and clawed most of it back.',5,5);

INSERT INTO public.clients (name,sort_order) VALUES
('Meridian Holdings',1),('Zafar Textiles',2),('Aafiyat Health Network',3),('Lahore Development Authority',4),('Punjab Agro Foods',5),('Askari Commercial Group',6),('Habib Land',7),('Sarwar Developers',8),('Higher Education Department, Punjab',9),('Serena Hospitality Ventures',10);

INSERT INTO public.certifications (title,issuer,reference_no,description,issued_year,sort_order) VALUES
('PEC Constructor Licence — Category C-A','Pakistan Engineering Council','PEC/CONST/OPR/12847','Registered constructor licence permitting works of unlimited value in the building and civil works categories.',2024,1),
('ISO 9001:2015 Quality Management','SGS Pakistan','PK/QMS/44120','Certified quality management system covering design, procurement and construction.',2023,2),
('ISO 45001:2018 Occupational Health & Safety','SGS Pakistan','PK/OHS/44121','Certified occupational health and safety management system across all sites.',2023,3),
('Punjab Revenue Authority — Active Taxpayer','Federal Board of Revenue','NTN 4270183-6','Active taxpayer status maintained continuously since incorporation.',2025,4),
('Registered Builder & Developer','Lahore Development Authority','LDA/B&D/2231','Registered as a builder and developer with the Lahore Development Authority.',2022,5);

INSERT INTO public.awards (title,issuer,year,description,sort_order) VALUES
('Contractor of the Year — Punjab','Pakistan Construction Association',2024,'Recognised for on-time delivery performance across commercial projects in Punjab.',1),
('Safety Excellence Award','Pakistan Engineering Council',2023,'Awarded for completing four million site hours without a lost-time injury.',2),
('Top 500 Corporate Taxpayer','Federal Board of Revenue',2024,'Listed among Pakistan top corporate taxpayers in the construction sector.',3),
('Best Commercial Project — Gulberg Corporate Tower','Pakistan Property Awards',2024,'Awarded best delivered commercial development in Lahore.',4);

INSERT INTO public.milestones (year,title,description,sort_order) VALUES
('2004','AMARC founded in Lahore','Started as a three-person design and supervision practice working on private residences in Gulberg and Model Town.',1),
('2008','First turnkey construction contract','Moved from supervision into self-performed construction with a 12,000 sq ft commercial building in Johar Town.',2),
('2012','PEC constructor licence upgraded','Licence category raised, allowing tender participation on public-sector work of unlimited value.',3),
('2015','Karachi regional office opened','Opened on Shahrah-e-Faisal to serve Sindh clients directly rather than from Lahore.',4),
('2018','First infrastructure contract with LDA','Awarded the Ravi Road carriageway and drainage widening, the firm entry into public infrastructure.',5),
('2021','ISO 9001 and ISO 45001 certification','Formalised the quality and safety management systems that had been in internal use since 2016.',6),
('2023','Gulberg Corporate Tower delivered','Fourteen-storey grade-A office tower handed over nine weeks ahead of contract.',7),
('2025','AMARC Vantage launched','The firm largest own-account development to date launched on Main Boulevard.',8);

INSERT INTO public.posts (slug,title,excerpt,body,author,category,read_minutes,published_at,tags) VALUES
('construction-cost-per-square-foot-pakistan-2026','What it actually costs to build per square foot in Pakistan (2026)','Grey structure, finishing and turnkey rates for Lahore, Karachi and Islamabad — with the assumptions written down so you can check them.','Ask five contractors for a per-square-foot rate and you will get five numbers, because nobody agrees on what is included. Here is our current position, stated with the assumptions.

## Grey structure

Grey structure — foundation, frame, slabs, blockwork, plaster, conduiting and roof treatment, with no finishes — currently runs PKR 3,200 to 3,900 per square foot of covered area in Lahore for a standard residential build on good ground. Karachi runs slightly higher on steel logistics; Islamabad higher again on aggregate haulage.

Three things move that number more than anything else:

**Steel rate.** Deformed bar has been the single most volatile line item for four years. A PKR 20,000 per tonne swing moves a 1-kanal house by roughly PKR 180 per square foot.

**Soil.** A raft where a strip footing would have done adds eight to twelve per cent to substructure cost. This is exactly why we do not price a job before the borehole report.

**Span.** Every metre of clear span beyond about 5.5 metres costs disproportionately in slab depth and reinforcement.

## Finishing

Finishing is where the range explodes, because it is entirely specification-driven. PKR 2,400 per square foot buys a competent, durable, unremarkable finish. PKR 6,000 buys imported stone, bespoke joinery and premium sanitary ware. Above PKR 9,000 you are in bespoke territory and per-square-foot rates stop being a useful way to think about it.

## Turnkey

For a well-specified residential turnkey job in Lahore, budget PKR 6,200 to 8,500 per square foot all-in. Anyone quoting materially below that is either excluding something or intends to claim it later as a variation.

## The honest advice

Do not select a contractor on rate. Select on the quality of the BOQ. A contractor who hands you a fifteen-page priced BOQ with named brands and quantities has thought about your project. A contractor who hands you a rate per square foot has not.','Nadia Sultan','Cost',6,'2026-07-14','["cost","residential","BOQ"]'::jsonb),
('lda-approval-process-explained','The LDA approval process, explained without the runaround','What you actually need to submit, in what order, and where the delays really come from.','Most people experience LDA approval as an opaque process that takes as long as it takes. It is not opaque; it is just sequential, and almost every delay comes from submitting an incomplete set.

## What you need before you start

Ownership documents (registry or allotment plus transfer letter), a fresh demarcation certificate, the approved site plan for the scheme, and a No Demand Certificate. Missing NDC is the single most common cause of a rejected first submission.

## The drawing set

Site plan, all floor plans, two sections, all elevations, and a structural stability certificate signed by a PEC-registered engineer. Drawings must be to LDA title-block format and the covered-area calculation on the sheet must reconcile exactly with the fee calculation. A mismatch of even a few square feet gets the file returned.

## Timeline

A complete residential submission on a clean title typically clears in six to ten weeks. Commercial takes longer because of the additional fire and parking scrutiny. The clock only starts on a complete file — which is why we run an internal completeness check against a written checklist before anything goes in.

## Where delays actually come from

In our experience: incomplete NDC, covered-area mismatch, demarcation older than six months, and structural certificates signed by an engineer whose PEC registration has lapsed. All four are avoidable in the week before submission.','Nadia Sultan','Regulation',5,'2026-05-22','["LDA","approvals","Lahore"]'::jsonb),
('why-soil-testing-is-not-optional','Why soil testing is not optional, even on a 10-marla plot','The borehole costs less than one per cent of your build. Skipping it has cost clients far more.','We get asked to waive the geotechnical investigation on small residential plots roughly once a month. The argument is always the same: the neighbours built without one and their houses are fine.

Here is the problem with that argument.

## Ground varies over short distances

Lahore alluvial deposits are not uniform. We have recorded a bearing capacity difference of more than forty per cent between two boreholes eleven metres apart on the same plot in Johar Town. Your neighbour ground is not your ground.

## Old fill is invisible from the surface

A substantial proportion of plots in newer sectors sit partly on filled ground — an old watercourse, a borrow pit, a demolished structure. Compacted properly, it is fine. Not compacted, it settles differentially, and differential settlement cracks a building in a way that is expensive and sometimes impossible to fix.

## Water table changes the design

If the water table is within the founding depth, you need dewatering during construction and waterproofing detail afterward. Discovering this at excavation stage rather than at design stage is the difference between a planned cost and an emergency one.

## The economics

Three boreholes to fifteen metres with laboratory classification costs a fraction of one per cent of a typical build. A raft you did not need costs eight to twelve per cent. An underpinning remedy after settlement costs more than either and takes months.

Do the test.','Bilal Cheema','Engineering',4,'2026-03-08','["geotechnical","soil","residential"]'::jsonb),
('passive-cooling-punjab-climate','Designing for 47 degrees: passive cooling that actually works in Punjab','Orientation, mass and shading will cut your cooling load before you spend a rupee on equipment.','Air conditioning is treated as the answer to Punjab summer. It is the last answer, not the first. Four design decisions, made before anything is built, reduce the cooling load substantially — and they cost nothing extra if made early.

## Orientation

The west elevation is the problem. Late-afternoon sun on a west-facing glazed wall in June drives peak cooling load. Where the plot allows, put service spaces — stairs, stores, washrooms — on the west and habitable rooms north and east.

## Thermal mass, correctly placed

Mass on the outside of insulation stores heat and re-radiates it into the room at night, which is the opposite of what you want. Mass on the inside of insulation buffers the daily swing. In practice this means insulating on the outer face of the wall, not the inner.

## Shading over glazing specification

A horizontal fin that keeps summer sun off the glass does more than any glass coating. The geometry is straightforward: size the projection for the June solar altitude at your latitude and it self-adjusts to admit winter sun.

## Courtyards and stack ventilation

The traditional courtyard house works because a shaded courtyard becomes a cool-air reservoir and drives cross ventilation through the plan. It is a genuinely good climatic response and it is why we designed AMARC Courtyard Homes around it rather than treating the courtyard as a decorative gesture.

Do these four things and the mechanical load drops far enough to change the plant size — which pays for itself in equipment cost before it ever touches your electricity bill.','Ayesha Rauf','Design',5,'2026-01-19','["design","climate","sustainability"]'::jsonb)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.jobs (slug,title,department,location,employment_type,experience,summary,description,responsibilities,requirements,sort_order) VALUES
('site-engineer-lahore','Site Engineer','Construction','Lahore','Full time','3–6 years','Site engineer for an active high-rise commercial project in Gulberg.','We are looking for a site engineer to join the delivery team on an active commercial project in Lahore. You will report to the project manager and be responsible for setting out, quality control and daily progress reporting.','["Setting out and level control","Daily progress reporting and photographic record","Material inspection and QA/QC documentation","Coordination with subcontractors and consultants","Enforcement of site HSE requirements"]'::jsonb,'["B.Sc. Civil Engineering from an HEC-recognised university","PEC registration","3–6 years of building construction experience","Working knowledge of AutoCAD and MS Project","Willingness to be site-based six days a week"]'::jsonb,1),
('structural-design-engineer','Structural Design Engineer','Engineering','Lahore','Full time','2–5 years','RCC and steel design engineer for the in-house structural team.','Join the structural team designing RCC and steel frames for buildings up to twenty storeys. You will work in ETABS and SAFE and be mentored toward stamping authority.','["Structural analysis and modelling in ETABS and SAFE","Member design to BCP and ACI","Reinforcement detailing and bar bending schedules","Coordination with the architecture studio","Site queries and RFI responses"]'::jsonb,'["B.Sc. or M.Sc. in Structural or Civil Engineering","PEC registration","Proficiency in ETABS, SAFE and AutoCAD","Understanding of BCP Seismic Provisions 2007"]'::jsonb,2),
('quantity-surveyor','Quantity Surveyor','Commercial','Karachi','Full time','4–8 years','Quantity surveyor for the Sindh regional commercial team.','Handle BOQ preparation, rate analysis, interim valuations and variation control across projects in Sindh.','["BOQ preparation and vetting","Rate analysis and subcontractor comparison","Interim payment applications and certification","Variation and claim documentation","Monthly cost reporting"]'::jsonb,'["B.Sc. Civil Engineering or B.Tech Quantity Surveying","4–8 years on building projects","Strong Excel and Candy or Primavera experience","Familiarity with FIDIC and PEC standard forms"]'::jsonb,3)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.tenders (title,reference_no,category,description,published_on,closes_at,sort_order) VALUES
('Supply of Deformed Steel Bar — Gulberg Projects','AMARC/TND/2026/014','Materials','Supply of Grade 60 deformed steel bar, sizes 10mm to 25mm, for ongoing Lahore projects. Mill test certificates mandatory with every consignment.','2026-08-01','2026-09-15',1),
('Aluminium & Glazing Subcontract — AMARC Vantage','AMARC/TND/2026/015','Subcontract','Design, supply and installation of unitised curtain wall and aluminium windows for a B2+G+22 mixed-use tower in Gulberg III. Prequalification required.','2026-08-12','2026-09-30',2);

INSERT INTO public.faqs (question,answer,category,sort_order) VALUES
('How do I get a price for my project?','Send us the plot size, location, approximate covered area and a rough brief through the contact form. We respond in writing within two working days with either a budget range or a list of what we need to price it properly. We do not give verbal per-square-foot quotes.','Getting started',1),
('Do you work on a fixed price or cost-plus basis?','Both. Private residential clients usually prefer a fixed price against a frozen BOQ. Institutional and industrial clients often prefer cost-plus with an agreed management fee and open-book accounting.','Commercial',2),
('What is included in your grey structure rate?','Excavation, foundation, RCC frame and slabs, blockwork, internal and external plaster, electrical and plumbing conduiting, roof treatment and waterproofing. It excludes all finishes, fixtures and fittings.','Commercial',3),
('How long does a 1-kanal house take?','Twelve to sixteen months from mobilisation to handover for a standard specification, assuming approvals are already in place. Higher-specification finishes and imported materials extend this.','Construction',4),
('Do you handle LDA, SBCA and CDA approvals?','Yes. Authority submission and approval tracking is included in our architectural service in Lahore, Karachi, Islamabad, Rawalpindi, Faisalabad and Multan.','Approvals',5),
('What warranty do you provide?','A twelve-month defects liability period from practical completion as standard, plus a ten-year structural warranty on projects where we carried out both design and construction.','After handover',6),
('Can I pay for a development in instalments?','Yes. Our developments run on 36 to 48 month instalment plans with a booking amount, monthly instalments and half-yearly balloon payments. The full schedule is published on each development page.','Real estate',7),
('Are buyer payments protected?','Payments on AMARC developments are held in a designated project account and buyer agreements carry a liquidated damages clause covering late handover.','Real estate',8);

INSERT INTO public.downloads (title,description,category,file_size,sort_order) VALUES
('AMARC Company Profile 2026','Full corporate profile including licences, project list, organisation chart and plant register.','Corporate','4.2 MB',1),
('Project List — Completed & Ongoing','Tabular list of all projects with client, value, dates and status.','Corporate','860 KB',2),
('AMARC Vantage Brochure','Floor plates, unit types, amenities and payment plan.','Development','12.8 MB',3),
('Vendor Prequalification Form','Form for suppliers and subcontractors seeking registration with AMARC.','Procurement','320 KB',4);

INSERT INTO public.page_seo (path,title,description) VALUES
('/','AMARC Engineering & Construction | Builders in Lahore, Karachi & Islamabad','Turnkey construction, architectural and structural design across Pakistan since 2004. PEC-licensed, ISO 9001 and 45001 certified. 184 projects delivered.'),
('/services','Construction & Engineering Services in Pakistan | AMARC','Nine in-house disciplines — architecture, structural design, construction, project management, real estate, materials, contracts, soil testing and interiors.'),
('/projects','Our Projects — Completed & Ongoing | AMARC Construction','Browse 184 completed and 23 ongoing construction projects across Lahore, Karachi, Islamabad, Faisalabad and Multan, filterable by sector, city and status.'),
('/about','About AMARC Engineering & Construction Company','Founded in Lahore in 2004. PEC-licensed constructor with in-house architecture, structural engineering and self-performed construction teams.'),
('/contact','Contact AMARC | Offices in Lahore, Karachi & Islamabad','Request a quote or visit one of our three regional offices. Written response to every enquiry within two working days.')
ON CONFLICT (path) DO NOTHING;